version: 2

sphinx:
  configuration: docs/conf.py  # Sphinx 설정 파일 경로

python:
  version: 3.11  # 사용하고자 하는 Python 버전

build:
  image: 'readthedocs/sphinx-build'  # ReadTheDocs에서 제공하는 빌드 이미지
  tools:
    - sphinx  # Sphinx를 빌드 도구로 설정
